# Generated by Django 3.2.5 on 2021-07-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=100)),
                ('s_roll_no', models.CharField(max_length=100)),
                ('s_regd_no', models.CharField(max_length=100)),
                ('s_address', models.CharField(max_length=100)),
            ],
        ),
    ]
